name: Generate Index.json

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Python generator
        run: python .github/scripts/generate_index.py

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.json
          git diff --cached --quiet || git commit -m "chore: update Index.json"
          git push origin main